version: '3.9'
services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - gwide-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/data

volumes:
  gwide-db:
